config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :mangas
  get 'mangas/:id/chapters/:chapter', to: 'mangas#chapter', as: 'chapter'
  get 'mangas/:location/:chapter/:image_name',
      to: 'mangas#image',
      as: :chapter_image,
      constraints: { filename: /[^\/]+/ }
  root to: "pages#home"

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/manga.rb
class Manga < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :thumbnail, presence: true
  validates :banner, presence: true
  validates :poster, presence: true

  def chapters
    MangaBrowser.albums(location)
  end

  def chapter_images(chapter)
    MangaBrowser.images_in_album(chapter, location)
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  allow_unauthenticated_access

  def index
    @test = MangaBrowser.albums

    @mangas = Manga.all.order(name: :asc)
  end

  def create
    @manga = Manga.new(manga_params)

    if @manga.save
      # redirect_to @password
      redirect_to mangas_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @manga = Manga.new
  end

  def show
    @manga = Manga.find(params[:id])
  end

  def edit
    @manga = Manga.find(params[:id])
  end

  def update
    @manga = Manga.find(params[:id])
    if @manga.update(manga_params)
      redirect_to @manga, notice: 'Manga was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @manga = Manga.find(params[:id])
    # @manga.destroy
    redirect_to mangas_path
  end

  def chapter
    @manga = Manga.find(params[:id])
    @chapter = params[:chapter]
    @images = MangaBrowser.images_in_album(@chapter, @manga.location)
  end

  def image
    location = params[:location]
    chapter = params[:chapter]
    image_name  = params[:format].present? ? "#{params[:image_name]}.#{params[:format]}" : params[:image_name]
    file_path = Rails.root.join('storage', 'mangas', location, chapter, image_name)

    if File.exist?(file_path)
      send_file file_path, disposition: 'inline'
    else
      Rails.logger.error "File not found at: #{file_path}"
      head :not_found

    end
  end

  private

  def manga_params
    params.require(:manga).permit(:name, :description, :location, :thumbnail, :banner, :poster)
  end
end

app/helpers/mangas_helper.rb
module MangasHelper
  def temporary_image_url(location, chapter, image_name, expires_in: 1.hour)
    verifier = ActiveSupport::MessageVerifier.new(Rails.application.secret_key_base)
    payload = { location:, chapter:, image_name: }
    token = verifier.generate(payload, expires_in:)
    chapter_image_path(location:, chapter:, image_name:, token:)
  end
end

app/views/mangas/_form.html.erb
<% if manga.errors.any? %>
  <div class="p-4 mb-4 bg-red-100 border border-red-400 text-red-700 rounded">
    <h2 class="font-bold"><%= pluralize(manga.errors.count, "error") %> prohibited this manga from being saved:</h2>
    <ul class="list-disc pl-5 mt-2">
      <% manga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: manga, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4 %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail %>
  </div>

  <div class="field">
    <%= form.label :banner %>
    <%= form.text_field :banner %>
  </div>

  <div class="field">
    <%= form.label :poster %>
    <%= form.text_field :poster %>
  </div>

  <div class="actions">
    <%= form.submit submit %>
  </div>
<% end %>

app/views/mangas/chapter.html.erb
<h1><%= @manga.name %> Chapter <%= @chapter %></h1>

<%= link_to 'Manga Page', mangas_path %>
<%= link_to 'Back to Chapters', manga_path(@manga) %>

<div>
  <% @images.each do |image| %>
    <div class="photo-card">
      <%= image_tag temporary_image_url(@manga.location, @chapter, image), loading: "lazy" %>
    </div>
  <% end %>
</div>

app/views/mangas/edit.html.erb
<h1>Edit Manga</h1>

<%= link_to 'Manga Page', mangas_path %>

<%= render 'form', manga: @manga, submit: 'Update' %>

app/views/mangas/index.html.erb
<h1>Mangas</h1>
<%= link_to 'Add Manga', new_manga_path %>
<pre><%= @test %></pre>

<% @mangas.each do |manga| %>
  <p><%= manga.name %></p>
  <%= link_to 'Show', manga_path(manga) %>
<% end %>

app/views/mangas/new.html.erb
<h1>Add Manga</h1>

<%= link_to 'Manga Page', mangas_path %>

<%= render 'form', manga: @manga, submit: 'Create' %>

app/views/mangas/show.html.erb
<%= link_to 'Manga Page', mangas_path %>
<%= link_to 'Edit', edit_manga_path(@manga) %>

<h1><%= @manga.name %></h1>

<p><%= @manga.description %></p>
<p><%= @manga.location %></p>

<pre><%= @manga.chapters %></pre>

<% @manga.chapters.each do |chapter| %>
  <p><%= chapter %></p>
  <%= link_to 'Read', chapter_path(@manga, chapter) %>
<% end %>